config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :funds
  resources :accounts
  get 'dashboard/index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "dashboard#index"
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :group
  has_many :funds

  enum account_type: [:checking, :money_market, :credit_card]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fund.rb
class Fund < ApplicationRecord
  belongs_to :account
  belongs_to :group
  has_many :transactions

  enum recurring_interval: {daily: 10, weekly: 20, bi_weekly: 30, monthly: 40, quarterly: 50, semesterly: 60, yearly: 70}
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :users
  has_many :accounts
  has_many :funds
  has_many :transactions
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :fund, optional: true
  belongs_to :account, optional: true
  belongs_to :group

  enum transaction_type: [:income, :payment, :transfer]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :group
  has_many :accounts, through: :group
  has_many :funds, through: :group
  has_many :transactions, through: :group
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:group_id, :user_id, :name, :account_type, :reserve)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/funds_controller.rb
class FundsController < ApplicationController
  before_action :set_fund, only: [:show, :edit, :update, :destroy]

  # GET /funds
  # GET /funds.json
  def index
    @funds = Fund.all
  end

  # GET /funds/1
  # GET /funds/1.json
  def show
  end

  # GET /funds/new
  def new
    @fund = Fund.new
  end

  # GET /funds/1/edit
  def edit
  end

  # POST /funds
  # POST /funds.json
  def create
    @fund = Fund.new(fund_params)

    respond_to do |format|
      if @fund.save
        format.html { redirect_to @fund, notice: 'Fund was successfully created.' }
        format.json { render :show, status: :created, location: @fund }
      else
        format.html { render :new }
        format.json { render json: @fund.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funds/1
  # PATCH/PUT /funds/1.json
  def update
    respond_to do |format|
      if @fund.update(fund_params)
        format.html { redirect_to @fund, notice: 'Fund was successfully updated.' }
        format.json { render :show, status: :ok, location: @fund }
      else
        format.html { render :edit }
        format.json { render json: @fund.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funds/1
  # DELETE /funds/1.json
  def destroy
    @fund.destroy
    respond_to do |format|
      format.html { redirect_to funds_url, notice: 'Fund was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fund
      @fund = Fund.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fund_params
      params.require(:fund).permit(:account_id, :group_id, :goal_amount, :goal_date, :recurring_interval)
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:fund_id, :account_id, :amount, :description, :transaction_date)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/funds_helper.rb
module FundsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/accounts/_form.html.haml
= form_for @account do |f|
  - if @account.errors.any?
    #error_explanation
      %h2= "#{pluralize(@account.errors.count, "error")} prohibited this account from being saved:"
      %ul
        - @account.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :account_type
    = f.number_field :account_type
  .field
    = f.label :reserve
    = f.text_field :reserve
  .actions
    = f.submit 'Save'

app/views/accounts/edit.html.haml
%h1 Editing account

= render 'form'

= link_to 'Show', @account
\|
= link_to 'Back', accounts_path

app/views/accounts/index.html.haml
%h1 Listing accounts

%table
  %thead
    %tr
      %th Name
      %th Account type
      %th Reserve
      %th
      %th
      %th

  %tbody
    - @accounts.each do |account|
      %tr
        %td= account.name
        %td= account.account_type
        %td= account.reserve
        %td= link_to 'Show', account
        %td= link_to 'Edit', edit_account_path(account)
        %td= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Account', new_account_path

app/views/accounts/new.html.haml
%h1 New account

= render 'form'

= link_to 'Back', accounts_path

app/views/accounts/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @account.name
%p
  %b Account type:
  = @account.account_type
%p
  %b Reserve:
  = @account.reserve

= link_to 'Edit', edit_account_path(@account)
\|
= link_to 'Back', accounts_path

app/views/dashboard/index.html.haml
%h1 Dashboard#index
%p Find me in app/views/dashboard/index.html.erb

app/views/funds/_form.html.haml
= form_for @fund do |f|
  - if @fund.errors.any?
    #error_explanation
      %h2= "#{pluralize(@fund.errors.count, "error")} prohibited this fund from being saved:"
      %ul
        - @fund.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :account_id, "Account"
    = f.select :account_id, f.object.group.accounts.map { |a| [ a.name, a.id ] }
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :goal_amount
    = f.text_field :goal_amount
  .field
    = f.label :goal_date
    = f.text_field :goal_date
  .field
    = f.label :recurring_interval
    = f.number_field :recurring_interval
  .actions
    = f.submit 'Save'

app/views/funds/edit.html.haml
%h1 Editing fund

= render 'form'

= link_to 'Show', @fund
\|
= link_to 'Back', funds_path

app/views/funds/index.html.haml
%h1 Listing funds

%table
  %thead
    %tr
      %th Name
      %th Account
      %th Goal amount
      %th Goal date
      %th Recurring interval
      %th
      %th
      %th

  %tbody
    - @funds.each do |fund|
      %tr
        %td= fund.name
        %td= fund.account.name
        %td= fund.goal_amount
        %td= fund.goal_date
        %td= fund.recurring_interval
        %td= link_to 'Show', fund
        %td= link_to 'Edit', edit_fund_path(fund)
        %td= link_to 'Destroy', fund, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Fund', new_fund_path

app/views/funds/new.html.haml
%h1 New fund

= render 'form'

= link_to 'Back', funds_path

app/views/funds/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @fund.name
%p
  %b Account:
  = @fund.account.name
%p
  %b Description:
  = @fund.description
%p
  %b Goal amount:
  = @fund.goal_amount
%p
  %b Goal date:
  = @fund.goal_date
%p
  %b Recurring interval:
  = @fund.recurring_interval

= link_to 'Edit', edit_fund_path(@fund)
\|
= link_to 'Back', funds_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Budgetize
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %p.notice= notice
    %p.alert= alert
    = yield

app/views/transactions/_form.html.haml
= form_for @transaction do |f|
  - if @transaction.errors.any?
    #error_explanation
      %h2= "#{pluralize(@transaction.errors.count, "error")} prohibited this transaction from being saved:"
      %ul
        - @transaction.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :fund
    = f.select :fund_id, f.object.group.funds.map {|fund| [fund.name, fund.id]}
  .field
    = f.label :account
    = f.select :account_id, f.object.group.accounts.map {|account| [account.name, account.id]}
  .field
    = f.label :amount
    = f.text_field :amount
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :transaction_date
    = f.text_field :transaction_date
  .field
    = f.label :transaction_type
    = f.select :transaction_type, Transaction.transaction_types.keys
  .actions
    = f.submit 'Save'

app/views/transactions/edit.html.haml
%h1 Editing transaction

= render 'form'

= link_to 'Show', @transaction
\|
= link_to 'Back', transactions_path

app/views/transactions/index.html.haml
%h1 Listing transactions

%table
  %thead
    %tr
      %th Fund
      %th Account
      %th Amount
      %th Description
      %th Transaction Date
      %th Transaction Type
      %th
      %th
      %th

  %tbody
    - @transactions.each do |transaction|
      %tr
        %td= transaction.fund&.name
        %td= transaction.account&.name
        %td= transaction.amount
        %td= transaction.description
        %td= transaction.transaction_date
        %td= transaction.transaction_type
        %td= link_to 'Show', transaction
        %td= link_to 'Edit', edit_transaction_path(transaction)
        %td= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Transaction', new_transaction_path

app/views/transactions/new.html.haml
%h1 New transaction

= render 'form'

= link_to 'Back', transactions_path

app/views/transactions/show.html.haml
%p#notice= notice

%p
  %b Fund:
  = @transaction.fund.name
%p
  %b Account:
  = @transaction.account.name
%p
  %b Amount:
  = @transaction.amount
%p
  %b Description:
  = @transaction.description
%p
  %b Transaction date:
  = @transaction.transaction_date
%p
  %b Transaction type:
  = @transaction.transaction_type

= link_to 'Edit', edit_transaction_path(@transaction)
\|
= link_to 'Back', transactions_path